FROM python:3.8-slim-buster

RUN mkdir -p /tradecoreapplication

WORKDIR /tradecoreapplication

COPY ./requirements.txt /tradecoreapplication/requirements.txt

RUN pip install -r requirements.txt

COPY . /tradecoreapplication