version: "3"
services:

  tradecore:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8000:8000"
    container_name: "tradecore"
    volumes:
      - .:/tradecoreapplication
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_HOST=tradecore-db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - tradecore-db

  tradecore-db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: celery -A tradecoreproject worker -l info
    volumes:
      - .:/tradecoreapplication
    depends_on:
      - redis
      - tradecore-db

